NUTELLA/account/urls.py
""" urls form the account app """
from django.urls import path
from . import views # import views so we can use them in urls.

app_name = 'account'

urlpatterns = [
    path('', views.account, name='index'),
    path('profile', views.profile, name='profile'),
    path('favorites', views.favorites, name='favorites'),
    path('log_out', views.log_out, name='logout')
]

NUTELLA/catalog/urls.py
""" catalog app urls """
from django.urls import path

from . import views # import views so we can use them in urls.

app_name = 'catalog'

urlpatterns = [
    path('', views.catalog, name='index'),
    path('search', views.search, name='search'),
    path('favorite/<str:id>', views.favorite, name='favorite'),
    path('notices/', views.notices, name='notices'),
    path('substitute', views.substitute, name='search-a-substitute'),
    path('catalog/<str:product_id>', views.product, name='detail'),
    path('autocomplete/', views.autocomplete, name='autocomplete')
]

NUTELLA/nutella_stop/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path
from catalog import views

app_name = 'nutella_stop'

urlpatterns = [
    path('', views.index, name='index'),
    path('', include('catalog.urls', namespace='catalog')),
    url(r'^account/', include('account.urls')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

NUTELLA/catalog/models.py
"""Create your models here."""
from django.db import models
from django.contrib.auth.models import User

class Category(models.Model):
    """Category class"""
    name = models.CharField(max_length=100, unique=True)
    def __str__(self):
        return self.name

class Product(models.Model):
    """Product class"""
    name = models.CharField(max_length=100, unique=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    description = models.CharField(max_length=1000)
    nutriscore = models.CharField(max_length=1)
    stores = models.CharField(max_length=200, null=False)
    image = models.URLField(null=False, default='image')
    brand = models.CharField(max_length=100, null=False)
    calories = models.IntegerField(null=True)
    lipids = models.FloatField(null=True)
    sugars = models.FloatField(null=True)
    proteins = models.FloatField(null=True)
    salts = models.FloatField(null=True)
    url_off = models.URLField(null=False)

    def __str__(self):
        return self.name

class Favorite(models.Model):
    """Favorite class"""
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

NUTELLA/catalog/views.py
"""views.py app catalog"""
# Create your views here.
from os import listdir
from os.path import isfile, join
import json
from django.http import HttpResponse
from django.template import loader
from django.contrib import messages
from django.shortcuts import redirect
from django.template.defaulttags import register
from .models import Product, Favorite
from .database import insert, results
# pylint: disable=no-member

@register.filter
def get_range(value):
    """range method"""
    return range(1, value)

def catalog(request):
    """catalog"""
    return redirect('index')

def notices(request):
    """notices page"""
    template = loader.get_template('catalog/notices.html')
    files = sorted([f for f in listdir('staticfiles/catalog/img') if \
    isfile(join('staticfiles/catalog/img', f))])
    content_picture = [
        "Emoticone triste par \
        <a href='https://www.flaticon.com/free-icon/crying_136366#term=cry&page=1&position=13' \
        target='_blank'>Flaticon</a>",
        "Colette par <a href='http://personnages-disney.com/Page%20Colette.html' \
        target='_blank'>personnages-disney</a>",
        "Logo de carotte par <a href='https://www.flaticon.com/free-icon/ \
        carrot_1041355#term=carrot&page=1&position=22' target='_blank'>Flaticon</a>",
        "Colette par <a href='https://company-82435.frontify.com/d/6Yy9WFJdtp8j/ \
        pur-beurre-style-guide#/introduction/Notre-identité' target='_blank'> Pur Beurre - \
        Charte Graphique </a>", "Logo de Pur Beurre par \
        <a href='https://company-82435.frontify.com/d/6Yy9WFJdtp8j/ \
        pur-beurre-style-guide#/introduction/Notre-identité' target='_blank'>\
        Pur Beurre - Charte Graphique </a>", "Logo de déconnexion par \
        <a href='https://www.flaticon.com/free-icon/logout_1828490#term=logout&page=1&position=28' \
        target='_blank'>Flaticon</a>", "Favicon logo Pur Beurre par \
        <a href='https://www.favicon-generator.org/'>favicon-generator</a>",
        "Fond d‘écran de la bannière par \
        <a href='https://unsplash.com/photos/eqsEZNCm4-c' target='_blank'> Olenka Kotyk</a>",
        "Rémy par <a href='https://company-82435.frontify.com/d/6Yy9WFJdtp8j/ \
        pur-beurre-style-guide#/introduction/Notre-identité' target='_blank'> \
        Pur Beurre - Charte Graphique </a>", "Logo d‘utilisateur par \
        <a href='https://www.flaticon.com/free-icon/carrot_1041355#term=carrot&page=1&position=22' \
        target='_blank'>Flaticon</a>"
    ]
    d = {x:y for x, y in zip(files, content_picture)}
    context = {
        'd' : d
    }
    return HttpResponse(template.render(context, request=request))

def index(request):
    """index page"""
    template = loader.get_template('catalog/index.html')
    insert()
    return HttpResponse(template.render(request=request))

def autocomplete(request):
    """autocomplete ajax"""
    if request.is_ajax():
        query_autocomplete = request.GET.get('term', '')
        products = Product.objects.filter(name__icontains=query_autocomplete).order_by('id')[:10]
        results = []
        global data
        for p in products:
            product_dict = {}
            product_dict = p.name
            results.append(product_dict)
        data = json.dumps(results)
    else:
        data = 'fail'
    return HttpResponse(data, 'application/json')

def substitute(request):
    """substitute page"""
    template = loader.get_template('catalog/substitute.html')
    global query_two
    query_two = None
    if request.GET.get('query_two') is not None:
        query_two = request.GET.get('query_two')
    query_two_infos = Product.objects.filter(name=query_two)
    global q_2
    for q_2 in query_two_infos:
        pass
    try:
        if q_2 is not None:
            subs = Product.objects.filter(category_id=q_2.category_id,
                                          nutriscore="A").order_by('id')
            if not subs:
                subs = Product.objects.filter(category_id=q_2.category_id,
                                              nutriscore="B").order_by('id')
            if not subs:
                subs = Product.objects.filter(category_id=q_2.category_id,
                                              nutriscore="C").order_by('id')
    except:
        messages.error(request, 'Ceci n‘est pas un produit. Veuillez réessayer')
        return redirect('index')
    global substitutes
    substitutes = {
        'query_two' : query_two,
        'q_2' : q_2,
        'subs' : subs,
    }
    return HttpResponse(template.render(substitutes, request=request))

def favorite(request, id):
    """favorite add"""
    messages.success(request, 'Le produit a été ajouté à vos favoris.')
    current_user = request.user
    Favorite.objects.get_or_create(user_id=current_user.id, product_id=id)
    return redirect('index')

def search(request):
    """search page"""
    template = loader.get_template('catalog/search.html')
    if request.GET.get('query_one') is not None:
        global query_one
        query_one = request.GET.get('query_one')
    query_one_infos = Product.objects.filter(name__contains=query_one).order_by('id')
    message = "{}".format(query_one)
    global msg
    msg = {
        'message' : message,
        'query_one_infos' : query_one_infos,
    }
    return HttpResponse(template.render(msg, request=request))

def product(request, product_id):
    """product page"""
    template = loader.get_template('catalog/product.html')
    results(product_id)
    message = results(product_id)
    return HttpResponse(template.render(message, request=request))

NUTELLA/catalog/templates/catalog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
{% include 'catalog/head.html' %}

<body id="page-top">
    {% include 'catalog/header.html' %}
    <!-- Masthead -->
    {% block content %}{% endblock %}
    {% include 'catalog/footer.html' %}
</body>

</html>

NUTELLA/catalog/templates/catalog/footer.html
{% load static %}
<!-- Footer -->
<footer class="bg-light py-5">
    <div class="d-flex justify-content-around">
        <a href="{% url 'catalog:notices' %}">Mentions légales</a>
        <a href="{% url 'catalog:index' %}#contact">Contact</a>
    </div>
</footer>
<!-- jQuery -->
<script src="{% static 'catalog/vendor/jquery/jquery.min.js' %}"></script>
<script src="https://code.jquery.com/jquery-migrate-3.0.0.min.js"></script>
<script src="{% static 'catalog/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="https://code.jquery.com/ui/1.10.2/jquery-ui.js" ></script>
<!-- Bootstrap Core JavaScript -->
<script src="{% static 'catalog/vendor/jquery-easing/jquery.easing.min.js' %}"></script>
<script src="{% static 'catalog/vendor/magnific-popup/jquery.magnific-popup.min.js' %}"></script>

<!-- Custom scripts for this template -->
<script src="{% static 'catalog/js/creative.min.js' %}"></script>

NUTELLA/catalog/templates/catalog/head.html
{% load static %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Pur Beurre</title>

    <!-- Font Awesome Icons -->
    <link href="{% static 'catalog/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic'
        rel='stylesheet' type='text/css'>

    <!-- Plugin CSS -->
    <link href="{% static 'catalog/vendor/magnific-popup/magnific-popup.css' %}" rel="stylesheet">
    
    <!-- Theme CSS - Includes Bootstrap -->
    <!-- Bootstrap Core CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'catalog/css/creative.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'catalog/css/index.css' %}" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="icon" type="image/png" href="{% static 'catalog/img/ms-icon-70x70.png' %}" />
    <link href="https://code.jquery.com/ui/1.10.2/themes/smoothness/jquery-ui.css" rel="Stylesheet"></link>

</head>

NUTELLA/catalog/templates/catalog/header.html
{% load static %}
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
    <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="{% url 'catalog:index' %}"><img
                src="{% static 'catalog/img/logo_pur_beurre.png' %}" /> Pur Beurre</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
            data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
            aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto my-2 my-lg-0">
                <li class="nav-item">
                    <!-- Search form -->
                    <form id="search" action="{% url 'catalog:search' %}" accept-charset="utf-8">
                        <input class="form-control" type="text" placeholder="Rechercher un produit" aria-label="Search"
                            name="query_one" autocomplete="off" required>
                    </form>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href="{% url 'account:profile' %}"><img
                                src="{% static 'catalog/img/user.svg' %}" height="30px" alt="user"></a>
                    </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="{% url 'account:favorites' %}"><img
                            src="{% static 'catalog/img/carrot.svg' %}" height="30px" alt="carotte"></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="{% url 'account:logout' %}"><img src="{% static 'catalog/img/logout.svg' %}" height="30px" alt="carotte"></a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="{% url 'account:index' %}"><img
                            src="{% static 'catalog/img/user.svg' %}" height="30px" alt="user"></a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

NUTELLA/catalog/templates/catalog/index.html
{% extends 'catalog/base.html' %}
{% load static %}
{% block content %}
{% autoescape off %}
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js"></script>
<script>
  $(document).ready(function () {
    $(function () {
      $('.basicAutoComplete').autocomplete({
        source: "autocomplete/",
        minLength: 2,
      });
    });
  });
</script>
{% endautoescape %}
<header class="masthead">
  <div class="container h-100">
    <div class="row h-100 align-items-center justify-content-center text-center">
      <div class="col-lg-10 align-self-end">
        {% if messages %}
        {% for msg in messages %}
        <div class="alert alert-info alert-dismissable">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          {{msg.message}}
        </div>
        {% endfor %}
        {% endif %}
        <h1 class="text-uppercase text-white font-weight-bold">Du gras oui, mais de qualité !
        </h1>
        <hr class="divider my-4">
      </div>
      <div class="col-lg-8 align-self-baseline">
        <h2 class="text-white-75 font-weight-light mb-5">Trouvez un produit de substitution pour ce que vous
          consommez tous les jours.
        </h2>
        <!-- Search form -->
        <form id="search-a-substitute" action="{% url 'catalog:search-a-substitute' %}" method="get"
          accept-charset="utf-8">
          <div class="input-group md-form form-sm form-1 pl-0">
            <input class="form-control basicAutoComplete" type="text" autocomplete="off"
              data-url="testdata/test-select-simple.json"
              placeholder="Trouver un produit de substitution parmi la variété de produits ci-dessous..."
              aria-label="Search" name="query_two">
            <input class="btn btn-primary" type="submit" value="Submit">
          </div>
        </form>
      </div>
    </div>
  </div>
</header>
<section id="services">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-8 text-center">
        <h2 class="mt-0">Colette et Rémy</h2>
        <hr class="divider my-4">
        <p class="text-muted mb-5"><em>Pur Beurre est l'initiative de deux amoureux de la gastronomie
            française,
            Colette Tatou et Rémy, que vous avez déjà certainement rencontrés dans notre excellent
            restaurant Ratatouille.</em></p>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-lg-6 col-md-6 text-center">
        <div class="service-box mt-5 mx-auto">
          <img src="{% static 'catalog/img/colette-tatou-full.png' %}" height="180" alt="Colette">
          <h3 class="mb-3">Colette</h3>
          <p class="text-muted mb-0 text-justify"><b>"Nous aimons tous manger, surtout en France !
              Personnellement, une baguette fraîche, du bon fromage de chèvre et un bon vin rouge
              me
              suffisent amplement.
              Comme tout le monde, je fais mes courses au supermarché.
              Mais petit à petit je me suis rendue compte, surtout lorsque nous avons ouvert le
              restaurant,
              que je pouvais remplacer les produits aseptisés que j'avais l'habitude d'acheter par
              de
              bons
              produits du terroir. Et souvent pour le même prix !"</b></p>
        </div>
      </div>
      <div class="col-lg-6 col-md-6 text-center">
        <div class="service-box mt-5 mx-auto">
          <img src="{% static 'catalog/img/ratatouille-portrait.jpg' %}" height="180" alt="Rémy">
          <h3 class="mb-3">Rémy</h3>
          <p class="text-muted mb-0 text-justify"><b>"Pour ma part je me rendais déjà dans bien des
              magasins
              car j'aime beaucoup me balader, surtout dans les caves et les cuisines.
              Je connaissais par coeur le contenu des boutiques bio (dont je raffole) ainsi que
              les
              ingrédients de tous les aliments vendus.
              Lorsque Colette m'a demandé si elle pouvait remplacer son Nutella matinal par un
              aliment
              plus sain, je savais tout de suite où le trouver. L'idée de Pur Beurre était née
              !"</b></p>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- Call to Action Section -->
<section class="page-section bg-dark text-white" id="contact">
  <div class="container text-center">
    <div class="row justify-content-center">
      <div class="col-lg-8 text-center">
        <h2 class="mt-0">Contactez-nous !</h2>
        <hr class="divider my-4">
        <p class="mb-5">N'hésitez pas à nous contacter pour plus d'informations.</p>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-4 ml-auto text-center mb-5 mb-lg-0">
        <i class="fa fa-phone fa-3x mb-3 text-muted"></i>
        <div>00 00 00 00 00</div>
      </div>
      <div class="col-lg-4 mr-auto text-center">
        <i class="fa fa-envelope fa-3x mb-3 text-muted"></i>
        <!-- Make sure to change the email address in anchor text AND the link below! -->
        <a class="d-block" href="mailto:contact@yourwebsite.com">purbeurre@purbeurre.com</a>
      </div>
    </div>
  </div>
</section>
{% endblock %}

NUTELLA/catalog/templates/catalog/notices.html
{% extends 'catalog/base.html' %}
{% load static %}
{% block content %}
<header class="masthead">
    <div class="container h-100">
        <div class="row h-100 align-items-center justify-content-center text-center">
            <div class="col-lg-8 align-self-baseline">
                <h2 class="text-white-75 font-weight-light mb-5">Mentions légales
                </h2>
            </div>
        </div>
    </div>
</header>
<section id="services">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8 text-center">
                <h2 class="mt-0">Généralités</h2>
                <hr class="divider my-4">
                <p class="text-muted mb-5">Le site est réalisé dans le cadre du projet 8 de la formation de développeur
                    Python sur <a href="https://openclassrooms.com/" target="_blank">OpenClassrooms</a>.</p>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8 text-center">
                <h2 class="mt-0">Contact</h2>
                <hr class="divider my-4">
                <p class="text-muted mb-5">Colette et Rémy.</p>
                <p class="text-muted mb-5">Téléphone: 00.00.00.00.00</p>
                <p class="text-muted mb-5">E-mail: <a href="mailto:contact@yourwebsite.com">purbeurre@purbeurre.com</a>
                </p>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8 text-center">
                <h2 class="mt-0">Hébergement du site</h2>
                <hr class="divider my-4">
                <p class="text-muted mb-5">Le site est hébergé sur le serveur <a
                        href="https://dashboard.heroku.com/apps" target="_blank">Heroku</a>.</p>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8 text-center">
                <h2 class="mt-0">Droits d'auteur</h2>
                <hr class="divider my-4">
            </div>
            <div class="col-lg-8 text-center">
                <p class="text-muted mb-5">Template Bootstrap utilisé : <a
                        href="https://startbootstrap.com/themes/creative/" target="_blank">Creative</a>.</p>
            </div>
        </div>
        <div class="row">
            {% for key, value in d.items %}
            <div class="col-lg-6 col-md-6 text-center">
                <div class="service-box mt-5 mx-auto">
                    <img src="{% static 'catalog/img/' %}{{ key }}" height="180" alt="picture">
                    {% autoescape off %}
                    <p class="mb-3">{{value}}</p>
                    {% endautoescape %}
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock %}

NUTELLA/catalog/templates/catalog/search.html
{% extends 'catalog/base.html' %}
{% load static %}
{% block content %}
<header class="masthead">
    <div class="container h-100">
        <div class="row h-100 align-items-center justify-content-center text-center">
            <div class="col-lg-8 align-self-baseline">
                <h2 class="text-white-75 font-weight-light mb-5">{{ message }}
                </h2>
            </div>
        </div>
    </div>
</header>
<section id="services">
    {% if not query_one_infos %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8 text-center">
                <h2 class="mt-0"><em>Aucun produit n'a été trouvé pour la requête suivante : {{ message }}</em></h2>
                <img src="{% static 'catalog/img/Colette Tatou.png' %}">
            </div>
        </div>
    </div>
    {% endif %}
    <div class="container" id="tourpackages-carousel">
        <div class="row">
            {% for r in query_one_infos %}
            <div class="col-xs-18 col-sm-6 col-md-4">
                <div class="thumbnail">
                    <div class="caption">
                        <span class="{{ r.nutriscore }}">{{ r.nutriscore }}</span>
                        <img src="{{ r.image }}" height="200" width="100%">
                        <h4>{{ r.name }}</h4>
                        {% if r.description %}
                        <b>
                            <p><em>{{ r.description }}</em></p>
                        </b>
                        {% else %}
                        <b><em>Pas de description disponible </em></b><img src="{% static 'catalog/img/136366.svg' %}"
                            height="30">
                        <br />
                        {% endif %}
                        <p><a href="{% url 'catalog:detail' r.id %}" class="btn btn-info btn-xs" role="button">En
                                savoir plus sur l'aliment</a>
                            {% if user.is_authenticated %}
                            <form method="post" action="{% url 'catalog:favorite' r.id  %}">
                                {% csrf_token %}
                                <i class="fa fa-floppy-o" aria-hidden="true"></i><input class="btn btn-default btn-xs"
                                    type="submit" value="Sauvegarder" id="{{ r.id }}" title="{{ r.id }}">
                            </form>
                        </p>
                        {% endif %}
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        <br />
    </div>
</section>
{% endblock %}

NUTELLA/catalog/templates/catalog/substitute.html
{% extends 'catalog/base.html' %}
{% load static %}
{% block content %}
{% autoescape off %}
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js"></script>
<script>
    $(document).ready(function () {
        ;
        $('header').css('background',
            'linear-gradient(rgba(0,0,0,.6), rgba(0,0,0,.6)),url({{ q_2.image }})');
        $('header').css('background-repeat', 'repeat');
        $('header').css('opacity', '1.1');
    });
</script>
{% endautoescape %}
<header class="masthead">
    <div class="container h-100">
        <div class="row h-100 align-items-center justify-content-center text-center">
            <div class="col-lg-8 align-self-baseline">
                <h2 class="text-white-75 font-weight-light mb-5">{{ q_2.name }}
                </h2>
            </div>
        </div>
    </div>
</header>
<section id="services">
    {% if not q_2 %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8 text-center">
                <h2 class="mt-0"><em>Aucun produit n'a été trouvé pour la requête suivante : {{ message }}</em></h2>
                <img src="{% static 'catalog/img/Colette Tatou.png' %}">
            </div>
        </div>
    </div>
    {% endif %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8 text-center">
                <em>{{ q_2.name }} a un nutriscore <b>{{ q_2.nutriscore }}</b></em>
                <h2 class="mt-0">Vous pouvez remplacer cet aliment par :</h2>
                <hr class="divider my-4">
                <p class="text-muted mb-5"></p>
            </div>
        </div>
    </div>
    <div class="container" id="tourpackages-carousel">
        <div class="row">
            {% for p in subs %}
            <div class="col-xs-18 col-sm-6 col-md-4">
                <div class="thumbnail">
                    <div class="caption">
                        <span class="{{ p.nutriscore }}">{{ p.nutriscore }}</span>
                        <img src="{{ p.image }}" height="200" width="100%">
                        <h4>{{ p.name }}</h4>
                        {% if p.description %}
                        <b>
                            <p><em>{{ p.description }}</em></p>
                        </b>
                        {% else %}
                        <b><em>Pas de description disponible </em></b><img src="{% static 'catalog/img/136366.svg' %}"
                            height="30">
                        <br />
                        {% endif %}
                        <p><a href="{% url 'catalog:detail' p.id %}" class="btn btn-info btn-xs" role="button">En
                                savoir plus sur l'aliment</a>
                            <br />
                            {% if user.is_authenticated %}
                            <form method="post" action="{% url 'catalog:favorite' p.id  %}">
                                {% csrf_token %}
                                <i class="fa fa-floppy-o" aria-hidden="true"></i><input class="btn btn-default btn-xs"
                                    type="submit" value="Sauvegarder" id="{{ p.id }}" title="{{ p.id }}">
                            </form>
                        </p>

                        {% endif %}
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        <br />
    </div>
</section>
{% endblock %}